---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: NAMESPACE-admin
  namespace: NAMESPACE
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: NAMESPACE-admin
  namespace: NAMESPACE
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: NAMESPACE-admin-rolebinding
  namespace: NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: NAMESPACE-admin
subjects:
- kind: ServiceAccount
  name: NAMESPACE-admin
  namespace: NAMESPACE
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: NAMESPACE-ClusterRole
  namespace: NAMESPACE
rules:
  - apiGroups: [""]
    resources: ["nodes","persistentvolumeclaims","persistentvolumes","pod"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["services/proxy","pods/portforward"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: NAMESPACE-ClusterRoleBinding
  namespace: NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: NAMESPACE-ClusterRole
subjects:
- kind: ServiceAccount
  name: NAMESPACE-admin
  namespace: NAMESPACE
- kind: ServiceAccount
  name: default
  namespace: NAMESPACE